### ISSUE TITLE
[Standalone] unable to authenticate with Gluetun

### ISSUE THREAD

**Issue by earthly-alien** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#17]
Hello,

I spun up the standalone version, since I use Hotio's qBittorrent container. My containers run on Unraid.

Your mod authenticates fine with qBittorrent container and fetches the port correctly, but it cannot authenticate with Gluetun. I keep getting `curl: (22) The requested URL returned error: 401`. I added the roles directive in Gluetun's config.toml, and I have another container that successfully authenticates using the same method to fetch the current IP.

I removed the other role and left the one just for this container - same result. I also changed to another, shorter API key generated through gluetun container - still getting 401.

Running `docker exec gluetun wget -q -O- /dev/tty http://localhost:8000/v1/openvpn/portforwarded` doesn't return anything (not the port, nor 0), but the port is definitely forwarded as seen in Gluetun's logs.

Any idea what could be wrong?

Edit: Running  `docker exec your-container-name curl -v -H "X-API-Key:RandomAPIKey" http://localhost:8000/v1/openvpn/portforwarded` returns the port successfully.

**Comment by t-anc** [comment]
Hi,

I'm not familiar wit Unraid, but I guess you have a configuration like a docker compose or something, could you post it here along with the logs from the mod and gluetun please ? The config.toml would be appreciated too.

(don't forget to remove any credential).

> Running `docker exec your-container-name curl -v -H "X-API-Key:RandomAPIKey" http://localhost:8000/v1/openvpn/portforwarded` returns the port successfully.

It's weird because that's more or less the same command made by the mod... I'll wait for your config and logs before making any wild guess.

Thank you,
Tanc

**Comment by earthly-alien** [comment]
Unraid uses `docker run`, it just presents it through templates in GUI to make it more user-friendly for people who aren't that familiar with docker. A `docker compose` plugin exists for it, and I do use it for stacks that are easier to manage that way, but I tend to prefer the templates for uniformity and update checks.

The variables I set are these:
Name: `gluetun-qbit-port-sync`
Image: `ghcr.io/linuxserver/baseimage-alpine:edge`
Extra parameters: `--net=container:gluetun`
DOCKER_MODS: `ghcr.io/t-anc/mod-qbittorrent-sync-port:main`
And the rest are `GSP_GTN_API_KEY`, `GSP_QBT_USERNAME` and `GSP_QBT_PASSWORD`.

Gluetun `config.toml`:
```
[[roles]]
name = "homepage"
routes = ["GET /v1/publicip/ip"]
auth = "apikey"
apikey = "random-api-key"
[[roles]]
name = "gluetun-qbit-port-sync"
routes = ["GET /v1/openvpn/portforwarded"]
auth = "apikey"
apikey = "random-api-key"
```

I do want to note that in the meantime, I changed it to `auth = "none"`, which works, but then there's no authentication.

Here's the log with authentication enabled:
```
++ curl --silent --fail --show-error http://localhost:8000/v1/openvpn/portforwarded
++ jq .port
curl: (22) The requested URL returned error: 401
+ GTN_PORT=
+ '[' -z '' ']'
+ log 'Error retrieving port from Gluetun API.'
++ date '+%x %T'
+ echo '12/20/24 12:34:35 [GSP] - Error retrieving port from Gluetun API.'
Ok.12/20/24 12:34:35 [GSP] - Error retrieving port from Gluetun API.
```

**Comment by t-anc** [comment]
Mmh the error seems to be the the `GSP_GTN_API_KEY` variable. 

My log, with auth and debug enabled, looks like this (I can see my APIKey in the debug log) : 

```
++ curl --silent --fail --show-error --cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt http://localhost:8080/api/v2/app/preferences
++ jq .listen_port
+ QBT_PORT=39408
+ '[' true ']'
++ curl --silent --fail --show-error -H X-API-Key:MySuperKey http://localhost:8000/v1/openvpn/portforwarded
+ GTN_PORTS='{"port":39408}'
```

Don't you get an error during init checks regarding the API key ?

**Comment by earthly-alien** [comment]
No, this is the entire loop:

```
+ :
+ SLEEP_TIME=60
+ '[' -n qbit-username ']'
+ '[' -n qbit-password ']'
+ qbt_login
+ curl --fail --silent --cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt --url http://localhost:8080/api/v2/auth/login --data username=qbit-username --data password=qbit-password
+ get_ports
+ case ${1,,} in
+ QBT=true
+ GTN=true
+ '[' true ']'
++ curl --silent --fail --show-error --cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt http://localhost:8080/api/v2/app/preferences
++ jq .listen_port
+ QBT_PORT=46708
+ '[' true ']'
++ curl --silent --fail --show-error http://localhost:8000/v1/openvpn/portforwarded
++ jq .port
curl: (22) The requested URL returned error: 401
+ GTN_PORT=
+ '[' -z '' ']'
+ log 'Error retrieving port from Gluetun API.'
++ date '+%x %T'
+ echo '12/20/24 15:38:59 [GSP] - Error retrieving port from Gluetun API.'
Ok.12/20/24 15:38:59 [GSP] - Error retrieving port from Gluetun API.
+ SLEEP_TIME=10
+ '[' -z 46708 ']'
+ '[' 10 -ne 10 ']'
+ sleep 10
```

As you can see, it's passing qBittorrent credentials set through the env variables, but not the Gluetun API key. It's completely missing from the command.

**Comment by t-anc** [comment]
It's weird, a bit like if you were running an old version of the mod, one without authentication. 

In order to handle multiple ports (#7), I renamed `GTN_PORT` into `GTN_PORTS` and then I process it (even with only one port). In my log, you can see that the variable getting the json result is `GTN_PORTS`, and in yours it's `GTN_PORT`. 

Gluetun's auth has been implemented after that (#10). + when I added gluetun's auth, I added a check for a 401 return during mod's initialisation  [here](https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod/blob/4755f391988002de5ed2969928ea07b25f115a41/root/etc/s6-overlay/s6-rc.d/svc-mod-gluetun-sync-port/run#L93), so you should either get a warning message (if `GTN_API_KEY` is not set) or an error message (in case of 401). 
The fact that you don't get either lead me to believe that you are running an older version. I don't know why, but it looks like you need to update the mod. (it's supposed to be automatic at container startup...).

Restart the standalone container and check the initialisation logs (ore paste it here, without debug mod). You should be able to see the mod's hash, and compare it with the one in this line (lastest one) :

```
[mod-init] t-anc/gsp-qbittorent-gluetun-sync-port-mod:main at sha256:f8d9ea59c757cecce625cee4f41bdc566236d795db2193ff9357d30fd574f0b2 has been previously applied skipping
```

In case you see this error : 
```
[mod-init] (ERROR) digest could not be fetched from ghcr.io
```

Then you can go check the [Troubleshooting section](https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#troubleshooting).

I'm sorry if this is a little bit confusing but I don't really understand how you got this error, so i'm trying things. :)

Hope we find the issue,
Regards,
Tanc

**Comment by earthly-alien** [comment]
> Restart the standalone container and check the initialisation logs (ore paste it here, without debug mod). You should be able to see the mod's hash, and compare it with the one in this line (lastest one) :
> 
> ```
> [mod-init] t-anc/gsp-qbittorent-gluetun-sync-port-mod:main at sha256:f8d9ea59c757cecce625cee4f41bdc566236d795db2193ff9357d30fd574f0b2 has been previously applied skipping
> ```

Thanks to this I found what the issue was. This is what I got:

```
[mod-init] t-anc/mod-qbittorrent-sync-port:main at sha256:0184a05d456091b48d19b7d62a538e958763bd88e912583dbea848b1a1c1e770 has been previously applied skipping
```

I didn't notice it at first, but when I went digging, I realized there are two different packages:
- `gsp-qbittorent-gluetun-sync-port-mod` which is the current one, referenced [here](https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod?tab=readme-ov-file#install-as-a-mod)
- `mod-qbittorrent-sync-port` which I installed (a previous version of this mod?), referenced [here](https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod?tab=readme-ov-file#install-as-a-standalone-container) in the compose file example.

After switching to the correct one, everything's working as expected. So the solution turned out to be pretty simple :)

Thanks for the help and the mod!

**Comment by t-anc** [comment]
> I didn't notice it at first, but when I went digging, I realized there are two different packages

Oh damn you are right ! This is an old and early project I need to delete, this has nothing to do here ! Sorry for that it's my fault.

Glad the issue is solved, I'll update the readme and remove this repo tomorrow.

**Comment by mrnetlex** [comment]
I just ran into the same issue as described here and spent a lot of time troubleshooting.  This thread was a lifesaver!  To save others the same frustration, could you add a warning to the README about the DOCKER_MODS change?
