### ISSUE TITLE
./run: line 72: [: Ok.200: integer expression expected

### ISSUE THREAD

**Issue by ibrokemypie** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#4]
I have added your mod and when I start my stack I get this message in the logs, before they continue on as if everything is fine. It seems like despite the logs indicating that ports were changed successfully, they actually are not because of this failed check.

```
qbittorrent  | ./run: line 72: [: Ok.200: integer expression expected
qbittorrent  | 08/23/24 17:40:45 [GSP] - Init checks passed. Listening for a change.
```

https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod/blob/b773d7d3a0a1145e9ed1af0ac6a2317c93d756b8/root/etc/s6-overlay/s6-rc.d/svc-mod-gluetun-sync-port/run#L72

**Comment by t-anc** [comment]
Hi.
This should not impact the mod, it should work as expected.

What I find strange is that there is a check, performing that command : 
`curl --write-out '%{http_code}' --silent --output /dev/null --url "${QBITTORRENT}/api/v2/app/version"`
This is supposed to return the response's HTTP status code (an integer) but it seems that you are getting `Ok.200` instead of just `200`. I can't find why online.

Could you share your compose file and your host OS please ? (don't forget to remove any credential).
You can also enable the debug log with the variable `GSP_DEBUG`, this could help to troubleshoot.

**Comment by t-anc** [comment]
It shoul be fixed by the last commit, could you try please ?

**Comment by ibrokemypie** [comment]
Seems to be fixed, ty!
